[package]
name = "qenex-os"
version = "0.1.0"
edition = "2021"
description = "QENEX Financial Operating System - Production Banking Infrastructure"
authors = ["QENEX Team"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/abdulrahman305/qenex-os"

[dependencies]
# Async runtime
tokio = { version = "1.35", features = ["full"] }
tokio-util = "0.7"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Cryptography
sha2 = "0.10"
rand = "0.8"
zeroize = { version = "1.7", features = ["derive"] }

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "decimal"] }
redis = { version = "0.24", features = ["tokio-comp"] }

# Networking
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
hyper = { version = "0.14", features = ["full"] }
tonic = "0.10"
prost = "0.12"

# Utilities
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "1.33", features = ["serde"] }
thiserror = "1.0"
anyhow = "1.0"

# Logging and monitoring
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
metrics = "0.22"
metrics-exporter-prometheus = "0.13"

# Configuration
config = "0.13"
clap = { version = "4.4", features = ["derive"] }

# Testing
mockall = "0.12"

# Machine Learning
candle-core = "0.3"
candle-nn = "0.3"
ndarray = "0.15"

# Additional async utilities
futures = "0.3"

[dev-dependencies]
tempfile = "3.8"
criterion = "0.5"

[[bin]]
name = "qenex-node"
path = "src/bin/node.rs"

[[bin]]
name = "qenex-cli"
path = "src/bin/cli.rs"

[features]
default = ["postgres", "redis"]
postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]
sqlite = ["sqlx/sqlite"]
redis = ["dep:redis"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.bench]
debug = true