# QENEX Banking OS Cargo Configuration
# Supports both bare-metal kernel and userspace banking applications

[build]
# Default target for banking applications
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-none]
# Bare-metal kernel target
runner = "bootimage runner"
rustflags = [
    "-C", "target-cpu=x86-64",
    "-C", "target-feature=-mmx,-sse,+soft-float",
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
    "-C", "panic=abort",
    "-Z", "unstable-options",
    "--cfg", "banking_kernel",
    "--cfg", "no_std_kernel"
]

[target.x86_64-unknown-linux-gnu]
# Standard userspace banking target
rustflags = [
    "-C", "target-cpu=x86-64-v3",
    "-C", "target-feature=+aes,+avx2,+fma",
    "-C", "link-arg=-Wl,-z,relro,-z,now",
    "-C", "link-arg=-Wl,-z,noexecstack",
    "--cfg", "banking_userspace"
]

# Banking-specific environment variables
[env]
BANKING_SECURITY_LEVEL = "MAXIMUM"
QUANTUM_SAFE_DEFAULT = "true"
HSM_INTEGRATION = "enabled"

# Banking kernel alias
[alias]
kernel-build = "build --target x86_64-unknown-none --features kernel --no-default-features"
kernel-test = "test --target x86_64-unknown-none --features kernel --no-default-features"
banking-build = "build --features banking-full --release"
security-audit = "audit --features security-max"

# Development profiles for banking compliance
[profile.dev]
debug = true
opt-level = 0
debug-assertions = true
overflow-checks = true
panic = "unwind"

[profile.release]
debug = false
opt-level = 3
debug-assertions = false
overflow-checks = false
panic = "abort"
lto = "fat"
codegen-units = 1
strip = false  # Keep symbols for banking audit requirements

[profile.kernel]
inherits = "release"
panic = "abort"
opt-level = 2  # Slightly lower optimization for banking safety
debug-assertions = true  # Keep assertions in kernel for safety
overflow-checks = true   # Critical for banking operations

[profile.banking-cert]
inherits = "release"
debug = true  # Banking certification requires debug symbols
debug-assertions = true
overflow-checks = true
incremental = false